apiVersion: v1
kind: Service
metadata:
  name: sentinel-server
  namespace: eclair-sentinel
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: sentinel
  ports:
  - port: 1947
    targetPort: 1947
