apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: test-runner-deployment
  namespace: zephyr-runner
spec:
  template:
    spec:
      organization: zephyrproject-rtos
      labels:
      - test-runner
      dockerdWithinRunnerContainer: true
      image: 724087766192.dkr.ecr.us-east-2.amazonaws.com/ci-zephyr-runner-arc:latest
      resources:
        limits:
          cpu: "16.0"
          memory: "32Gi"
        requests:
          cpu: "15.0"
          memory: "24Gi"
      volumeMounts:
      - mountPath: "/repo-cache"
        name: repo-cache
        readOnly: true
      - mountPath: "/var/lib/docker/image"
        name: docker-image
      - mountPath: "/var/lib/docker/overlay2"
        name: docker-overlay2
      volumes:
      - name: repo-cache
        hostPath:
          path: /pod-cache/repos
      - name: docker-image
        hostPath:
          path: /var/lib/docker-dind/image
      - name: docker-overlay2
        hostPath:
          path: /var/lib/docker-dind/overlay2
      nodeSelector:
        InstanceType: spot
      tolerations:
      - key: "spotInstance"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: test-runner-deployment-autoscaler
  namespace: zephyr-runner
spec:
  scaleTargetRef:
    kind: RunnerDeployment
    name: test-runner-deployment
  minReplicas: 1
  maxReplicas: 100
  scaleDownDelaySecondsAfterScaleOut: 600
  # scaleUpTriggers:
  # - githubEvent:
  #     workflowJob: {}
  #   duration: "15m"
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '1.0'
    scaleDownThreshold: '0.9'
    scaleUpAdjustment: 10
    scaleDownAdjustment: 5
