apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: test-runner-linux-arm64-4xlarge-deployment
  namespace: zephyr-runner
spec:
  template:
    spec:
      organization: zephyrproject-rtos
      labels:
      - test-runner-linux-arm64-4xlarge
      dockerdWithinRunnerContainer: true
      image: 724087766192.dkr.ecr.us-east-2.amazonaws.com/ci-zephyr-runner-arc:latest
      resources:
        limits:
          cpu: "16.0"
          memory: "32Gi"
        requests:
          cpu: "15.0"
          memory: "24Gi"
      volumeMounts:
      - mountPath: "/repo-cache"
        name: repo-cache
        readOnly: true
      - mountPath: "/var/lib/docker/image"
        name: docker-image
      - mountPath: "/var/lib/docker/overlay2"
        name: docker-overlay2
      volumes:
      - name: repo-cache
        hostPath:
          path: /pod-cache/repos
      - name: docker-image
        hostPath:
          path: /var/lib/docker-dind/image
      - name: docker-overlay2
        hostPath:
          path: /var/lib/docker-dind/overlay2
      nodeSelector:
        instanceType: spot
        instanceSize: 4xlarge
        instanceArch: arm64
        instanceOs: linux
      tolerations:
      - key: "spotInstance"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: test-runner-linux-arm64-4xlarge-deployment-autoscaler
  namespace: zephyr-runner
spec:
  scaleTargetRef:
    kind: RunnerDeployment
    name: test-runner-linux-arm64-4xlarge-deployment
  minReplicas: 0
  maxReplicas: 100
  scaleDownDelaySecondsAfterScaleOut: 60
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - zephyr-testing
    - sdk-ng-testing
