apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: zephyr-runner-linux-x64-xlarge-deployment
  namespace: zephyr-runner
spec:
  template:
    spec:
      organization: zephyrproject-rtos
      labels:
      - zephyr-runner
      - xlarge
      - zephyr-runner-linux-x64-xlarge
      dockerdWithinRunnerContainer: true
      image: 724087766192.dkr.ecr.us-east-2.amazonaws.com/ci-zephyr-runner-arc:v0.0.9
      resources:
        limits:
          cpu: "4.0"
          memory: "8Gi"
        requests:
          cpu: "3.5"
          memory: "5Gi"
      volumeMounts:
      - mountPath: "/repo-cache"
        name: repo-cache
        readOnly: true
      - mountPath: "/var/lib/docker/image"
        name: docker-image
      - mountPath: "/var/lib/docker/overlay2"
        name: docker-overlay2
      volumes:
      - name: repo-cache
        hostPath:
          path: /pod-cache/repos
      - name: docker-image
        hostPath:
          path: /var/lib/docker-dind/image
      - name: docker-overlay2
        hostPath:
          path: /var/lib/docker-dind/overlay2
      nodeSelector:
        instanceType: spot
        instanceSize: xlarge
        instanceArch: x64
        instanceOs: linux
      tolerations:
      - key: "spotInstance"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: zephyr-runner-linux-x64-xlarge-deployment-autoscaler
  namespace: zephyr-runner
spec:
  scaleTargetRef:
    kind: RunnerDeployment
    name: zephyr-runner-linux-x64-xlarge-deployment
  minReplicas: 0
  maxReplicas: 100
  scaleDownDelaySecondsAfterScaleOut: 60
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - zephyr
    - zephyr-bt-sig
    - sdk-ng
    - docker-image
