apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: main
  namespace: elastic-stack
spec:
  version: 8.5.3
  count: 2
  config:
    server.publicBaseUrl: https://kibana.zephyrproject.io
    xpack.security.authc.providers:
      basic.basic1:
        order: 0
      anonymous.anonymous1:
        order: 1
        credentials:
          username: "guest"
          password: "kibanaguest"
  elasticsearchRef:
    name: main
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            cpu: 1
