# cache-1 Service
apiVersion: v1
kind: Service
metadata:
  name: cache-1
  namespace: keydb-cache
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: keydb-cache-1
  ports:
  - port: 6379
    targetPort: 6379

---
# cache-2 Service
apiVersion: v1
kind: Service
metadata:
  name: cache-2
  namespace: keydb-cache
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: keydb-cache-2
  ports:
  - port: 6379
    targetPort: 6379

---
# cache-3 Service
apiVersion: v1
kind: Service
metadata:
  name: cache-3
  namespace: keydb-cache
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: keydb-cache-3
  ports:
  - port: 6379
    targetPort: 6379
